//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdfinal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point A_Match_Pos {
            get {
                return ((global::System.Drawing.Point)(this["A_Match_Pos"]));
            }
            set {
                this["A_Match_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size A_Match_Size {
            get {
                return ((global::System.Drawing.Size)(this["A_Match_Size"]));
            }
            set {
                this["A_Match_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Division_Pos {
            get {
                return ((global::System.Drawing.Point)(this["Division_Pos"]));
            }
            set {
                this["Division_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Division_Size {
            get {
                return ((global::System.Drawing.Size)(this["Division_Size"]));
            }
            set {
                this["Division_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point A_Propos_Pos {
            get {
                return ((global::System.Drawing.Point)(this["A_Propos_Pos"]));
            }
            set {
                this["A_Propos_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size A_Propos_Size {
            get {
                return ((global::System.Drawing.Size)(this["A_Propos_Size"]));
            }
            set {
                this["A_Propos_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AffJoueur_Pos {
            get {
                return ((global::System.Drawing.Point)(this["AffJoueur_Pos"]));
            }
            set {
                this["AffJoueur_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size AffJoueur_Size {
            get {
                return ((global::System.Drawing.Size)(this["AffJoueur_Size"]));
            }
            set {
                this["AffJoueur_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point A_Fiche_Pos {
            get {
                return ((global::System.Drawing.Point)(this["A_Fiche_Pos"]));
            }
            set {
                this["A_Fiche_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size A_Fiche_Size {
            get {
                return ((global::System.Drawing.Size)(this["A_Fiche_Size"]));
            }
            set {
                this["A_Fiche_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point A_Joueur_Pos {
            get {
                return ((global::System.Drawing.Point)(this["A_Joueur_Pos"]));
            }
            set {
                this["A_Joueur_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size A_Joueur_Size {
            get {
                return ((global::System.Drawing.Size)(this["A_Joueur_Size"]));
            }
            set {
                this["A_Joueur_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Classement_Pos {
            get {
                return ((global::System.Drawing.Point)(this["Classement_Pos"]));
            }
            set {
                this["Classement_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Classement_Size {
            get {
                return ((global::System.Drawing.Size)(this["Classement_Size"]));
            }
            set {
                this["Classement_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Match_Pos {
            get {
                return ((global::System.Drawing.Point)(this["Match_Pos"]));
            }
            set {
                this["Match_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Match_Size {
            get {
                return ((global::System.Drawing.Size)(this["Match_Size"]));
            }
            set {
                this["Match_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Mod_Joueur_Pos {
            get {
                return ((global::System.Drawing.Point)(this["Mod_Joueur_Pos"]));
            }
            set {
                this["Mod_Joueur_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Mod_Joueur_Size {
            get {
                return ((global::System.Drawing.Size)(this["Mod_Joueur_Size"]));
            }
            set {
                this["Mod_Joueur_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Mod_Equipe_Pos {
            get {
                return ((global::System.Drawing.Point)(this["Mod_Equipe_Pos"]));
            }
            set {
                this["Mod_Equipe_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Mod_Equipe_Size {
            get {
                return ((global::System.Drawing.Size)(this["Mod_Equipe_Size"]));
            }
            set {
                this["Mod_Equipe_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Settings_Pos {
            get {
                return ((global::System.Drawing.Point)(this["Settings_Pos"]));
            }
            set {
                this["Settings_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Setting_Size {
            get {
                return ((global::System.Drawing.Size)(this["Setting_Size"]));
            }
            set {
                this["Setting_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Form1_Pos {
            get {
                return ((global::System.Drawing.Point)(this["Form1_Pos"]));
            }
            set {
                this["Form1_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size Form1_Size {
            get {
                return ((global::System.Drawing.Size)(this["Form1_Size"]));
            }
            set {
                this["Form1_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point A_Equipe_Pos {
            get {
                return ((global::System.Drawing.Point)(this["A_Equipe_Pos"]));
            }
            set {
                this["A_Equipe_Pos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size A_Equipe_Size {
            get {
                return ((global::System.Drawing.Size)(this["A_Equipe_Size"]));
            }
            set {
                this["A_Equipe_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DGV_Alt_Color {
            get {
                return ((global::System.Drawing.Color)(this["DGV_Alt_Color"]));
            }
            set {
                this["DGV_Alt_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color DGV_Def_Color {
            get {
                return ((global::System.Drawing.Color)(this["DGV_Def_Color"]));
            }
            set {
                this["DGV_Def_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Header_Color {
            get {
                return ((global::System.Drawing.Color)(this["Header_Color"]));
            }
            set {
                this["Header_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Form_BG_Color {
            get {
                return ((string)(this["Form_BG_Color"]));
            }
            set {
                this["Form_BG_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BackColorFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["BackColorFormLocation"]));
            }
            set {
                this["BackColorFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Colors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Colors"]));
            }
            set {
                this["Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Text_Color {
            get {
                return ((global::System.Drawing.Color)(this["Text_Color"]));
            }
            set {
                this["Text_Color"] = value;
            }
        }
    }
}
