-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2014-11-23 20:18:32 AST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g


DROP TABLE Division CASCADE CONSTRAINTS;
DROP TABLE Equipe CASCADE CONSTRAINTS;
DROP TABLE FicheMatchJoueur CASCADE CONSTRAINTS;
DROP TABLE Joueurs CASCADE CONSTRAINTS;
DROP TABLE Match CASCADE CONSTRAINTS;


CREATE TABLE Division
  (
    NumDivision     NUMBER (4) NOT NULL ,
    Nom             VARCHAR2 (40) ,
    DateInscription DATE
  ) ;
ALTER TABLE Division ADD CONSTRAINT Division_PK PRIMARY KEY ( NumDivision ) ;

CREATE TABLE Equipe
  (
    NumEquipe        NUMBER (4) NOT NULL ,
    NumDivision      NUMBER (4) NOT NULL ,
    DateIntroduction DATE ,
    Logo BLOB ,
    Ville     VARCHAR2 (30) ,
    NomEquipe VARCHAR2 (20)
  ) ;
ALTER TABLE Equipe ADD CONSTRAINT Equipe_PK PRIMARY KEY ( NumEquipe ) ;

CREATE TABLE FicheMatchJoueur
  (
    NumMatch  NUMBER (4) NOT NULL ,
    NumJoueur NUMBER (4) NOT NULL ,
    NbPasses  NUMBER (2) ,
    NbButs    NUMBER (2)
  ) ;

CREATE TABLE Joueurs
  (
    NumJoueur     NUMBER (4) NOT NULL ,
    Nom           VARCHAR2 (30) ,
    Prenom        VARCHAR2 (30) ,
    DateNaissance DATE ,
    NumeroMaillot NUMBER (2) ,
    Photo BLOB ,
    Position  VARCHAR2 (10) ,
    NumEquipe NUMBER (4) NOT NULL
   
  ) ;
  
ALTER TABLE Joueurs ADD CONSTRAINT Joueurs_PK PRIMARY KEY ( NumJoueur ) ;

CREATE TABLE MATCH
  (
    NumMatch        NUMBER (4) NOT NULL ,
    EquipeReceveuse NUMBER (4) NOT NULL ,
    EquipeVisiteuse NUMBER (4) NOT NULL ,
    Dateheure       DATE ,
    Lieu            VARCHAR2 (30)
  ) ;
  
ALTER TABLE MATCH ADD CONSTRAINT Match_PK PRIMARY KEY ( NumMatch ) ;

ALTER TABLE Equipe ADD CONSTRAINT Equipe_Division_FK FOREIGN KEY ( NumDivision ) REFERENCES Division ( NumDivision ) ;

ALTER TABLE FicheMatchJoueur ADD CONSTRAINT FicheMatchJoueur_Joueurs_FK FOREIGN KEY ( NumJoueur ) REFERENCES Joueurs ( NumJoueur ) ;

ALTER TABLE FicheMatchJoueur ADD CONSTRAINT FicheMatchJoueur_Match_FK FOREIGN KEY ( NumMatch ) REFERENCES MATCH ( NumMatch ) ;

ALTER TABLE Joueurs ADD CONSTRAINT Joueurs_Equipe_FK FOREIGN KEY ( NumEquipe ) REFERENCES Equipe ( NumEquipe ) ;

ALTER TABLE MATCH ADD CONSTRAINT Match_Equipe_FK FOREIGN KEY ( EquipeReceveuse ) REFERENCES Equipe ( NumEquipe ) ;

ALTER TABLE MATCH ADD CONSTRAINT Match_Equipe_FKv1 FOREIGN KEY ( EquipeVisiteuse ) REFERENCES Equipe ( NumEquipe ) ;


CREATE SYNONYM SYNJOUEURS FOR JOUEURS;
GRANT SELECT ON SYNJOUEURS TO PUBLIC;
GRANT ALL ON SYNJOUEURS TO LEMAIREF;


CREATE VIEW FichePersonnelle AS(
SELECT JOUEURS.NUMJOUEUR,nom,prenom , equipe.nomequipe ,count(fichematchjoueur.nbbuts) as Nombrebuts,count(nbpasses) as nombrepasses
FROM JOUEURS
inner join equipe
on equipe.numequipe = joueurs.numequipe
inner join Match
on match.equipereceveuse = equipe.numequipe OR match.equipevisiteuse = equipe.NUMEQUIPE
inner join fichematchjoueur
on fichematchjoueur.nummatch = Match.NUMMATCH
group by JOUEURS.NUMJOUEUR ,nom,prenom , equipe.nomequipe);

